name: Trigger auto deployment for swiftfiddle-runner-functions-600

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/swiftfiddle-runner-functions-600-AutoDeployTrigger-aaf72874-b408-42b2-a379-c1adb3cbfb06.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS600_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS600_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS600_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS600_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS600_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-600
          resourceGroup: swiftfiddle
          imageToBuild: kishikawakatsumi/swiftfiddle-runner-functions-600:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


